// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Choice is the predicate function for choice builders.
type Choice func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)
