-- Create "questions" table
CREATE TABLE "questions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "reference_code" character varying NULL, "title" character varying NOT NULL, "content" text NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "choices" table
CREATE TABLE "choices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "content" character varying NOT NULL, "is_correct" boolean NOT NULL DEFAULT false, "question_choices" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "choices_questions_choices" FOREIGN KEY ("question_choices") REFERENCES "questions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
