// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/choice"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/predicate"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/question"
)

// ChoiceUpdate is the builder for updating Choice entities.
type ChoiceUpdate struct {
	config
	hooks    []Hook
	mutation *ChoiceMutation
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (cu *ChoiceUpdate) Where(ps ...predicate.Choice) *ChoiceUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetContent sets the "content" field.
func (cu *ChoiceUpdate) SetContent(s string) *ChoiceUpdate {
	cu.mutation.SetContent(s)
	return cu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (cu *ChoiceUpdate) SetNillableContent(s *string) *ChoiceUpdate {
	if s != nil {
		cu.SetContent(*s)
	}
	return cu
}

// SetIsCorrect sets the "is_correct" field.
func (cu *ChoiceUpdate) SetIsCorrect(b bool) *ChoiceUpdate {
	cu.mutation.SetIsCorrect(b)
	return cu
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (cu *ChoiceUpdate) SetNillableIsCorrect(b *bool) *ChoiceUpdate {
	if b != nil {
		cu.SetIsCorrect(*b)
	}
	return cu
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (cu *ChoiceUpdate) SetQuestionID(id int) *ChoiceUpdate {
	cu.mutation.SetQuestionID(id)
	return cu
}

// SetQuestion sets the "question" edge to the Question entity.
func (cu *ChoiceUpdate) SetQuestion(q *Question) *ChoiceUpdate {
	return cu.SetQuestionID(q.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (cu *ChoiceUpdate) Mutation() *ChoiceMutation {
	return cu.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (cu *ChoiceUpdate) ClearQuestion() *ChoiceUpdate {
	cu.mutation.ClearQuestion()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChoiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChoiceUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChoiceUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChoiceUpdate) check() error {
	if v, ok := cu.mutation.Content(); ok {
		if err := choice.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Choice.content": %w`, err)}
		}
	}
	if cu.mutation.QuestionCleared() && len(cu.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Choice.question"`)
	}
	return nil
}

func (cu *ChoiceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Content(); ok {
		_spec.SetField(choice.FieldContent, field.TypeString, value)
	}
	if value, ok := cu.mutation.IsCorrect(); ok {
		_spec.SetField(choice.FieldIsCorrect, field.TypeBool, value)
	}
	if cu.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuestionTable,
			Columns: []string{choice.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuestionTable,
			Columns: []string{choice.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChoiceUpdateOne is the builder for updating a single Choice entity.
type ChoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChoiceMutation
}

// SetContent sets the "content" field.
func (cuo *ChoiceUpdateOne) SetContent(s string) *ChoiceUpdateOne {
	cuo.mutation.SetContent(s)
	return cuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (cuo *ChoiceUpdateOne) SetNillableContent(s *string) *ChoiceUpdateOne {
	if s != nil {
		cuo.SetContent(*s)
	}
	return cuo
}

// SetIsCorrect sets the "is_correct" field.
func (cuo *ChoiceUpdateOne) SetIsCorrect(b bool) *ChoiceUpdateOne {
	cuo.mutation.SetIsCorrect(b)
	return cuo
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (cuo *ChoiceUpdateOne) SetNillableIsCorrect(b *bool) *ChoiceUpdateOne {
	if b != nil {
		cuo.SetIsCorrect(*b)
	}
	return cuo
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (cuo *ChoiceUpdateOne) SetQuestionID(id int) *ChoiceUpdateOne {
	cuo.mutation.SetQuestionID(id)
	return cuo
}

// SetQuestion sets the "question" edge to the Question entity.
func (cuo *ChoiceUpdateOne) SetQuestion(q *Question) *ChoiceUpdateOne {
	return cuo.SetQuestionID(q.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (cuo *ChoiceUpdateOne) Mutation() *ChoiceMutation {
	return cuo.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (cuo *ChoiceUpdateOne) ClearQuestion() *ChoiceUpdateOne {
	cuo.mutation.ClearQuestion()
	return cuo
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (cuo *ChoiceUpdateOne) Where(ps ...predicate.Choice) *ChoiceUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChoiceUpdateOne) Select(field string, fields ...string) *ChoiceUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Choice entity.
func (cuo *ChoiceUpdateOne) Save(ctx context.Context) (*Choice, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChoiceUpdateOne) SaveX(ctx context.Context) *Choice {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChoiceUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChoiceUpdateOne) check() error {
	if v, ok := cuo.mutation.Content(); ok {
		if err := choice.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Choice.content": %w`, err)}
		}
	}
	if cuo.mutation.QuestionCleared() && len(cuo.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Choice.question"`)
	}
	return nil
}

func (cuo *ChoiceUpdateOne) sqlSave(ctx context.Context) (_node *Choice, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Choice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choice.FieldID)
		for _, f := range fields {
			if !choice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != choice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Content(); ok {
		_spec.SetField(choice.FieldContent, field.TypeString, value)
	}
	if value, ok := cuo.mutation.IsCorrect(); ok {
		_spec.SetField(choice.FieldIsCorrect, field.TypeBool, value)
	}
	if cuo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuestionTable,
			Columns: []string{choice.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuestionTable,
			Columns: []string{choice.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Choice{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
