// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/choice"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/predicate"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/question"
)

// QuestionUpdate is the builder for updating Question entities.
type QuestionUpdate struct {
	config
	hooks    []Hook
	mutation *QuestionMutation
}

// Where appends a list predicates to the QuestionUpdate builder.
func (qu *QuestionUpdate) Where(ps ...predicate.Question) *QuestionUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetReferenceCode sets the "reference_code" field.
func (qu *QuestionUpdate) SetReferenceCode(s string) *QuestionUpdate {
	qu.mutation.SetReferenceCode(s)
	return qu
}

// SetNillableReferenceCode sets the "reference_code" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableReferenceCode(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetReferenceCode(*s)
	}
	return qu
}

// ClearReferenceCode clears the value of the "reference_code" field.
func (qu *QuestionUpdate) ClearReferenceCode() *QuestionUpdate {
	qu.mutation.ClearReferenceCode()
	return qu
}

// SetTitle sets the "title" field.
func (qu *QuestionUpdate) SetTitle(s string) *QuestionUpdate {
	qu.mutation.SetTitle(s)
	return qu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableTitle(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetTitle(*s)
	}
	return qu
}

// SetContent sets the "content" field.
func (qu *QuestionUpdate) SetContent(s string) *QuestionUpdate {
	qu.mutation.SetContent(s)
	return qu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (qu *QuestionUpdate) SetNillableContent(s *string) *QuestionUpdate {
	if s != nil {
		qu.SetContent(*s)
	}
	return qu
}

// AddChoiceIDs adds the "choices" edge to the Choice entity by IDs.
func (qu *QuestionUpdate) AddChoiceIDs(ids ...int) *QuestionUpdate {
	qu.mutation.AddChoiceIDs(ids...)
	return qu
}

// AddChoices adds the "choices" edges to the Choice entity.
func (qu *QuestionUpdate) AddChoices(c ...*Choice) *QuestionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return qu.AddChoiceIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (qu *QuestionUpdate) Mutation() *QuestionMutation {
	return qu.mutation
}

// ClearChoices clears all "choices" edges to the Choice entity.
func (qu *QuestionUpdate) ClearChoices() *QuestionUpdate {
	qu.mutation.ClearChoices()
	return qu
}

// RemoveChoiceIDs removes the "choices" edge to Choice entities by IDs.
func (qu *QuestionUpdate) RemoveChoiceIDs(ids ...int) *QuestionUpdate {
	qu.mutation.RemoveChoiceIDs(ids...)
	return qu
}

// RemoveChoices removes "choices" edges to Choice entities.
func (qu *QuestionUpdate) RemoveChoices(c ...*Choice) *QuestionUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return qu.RemoveChoiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QuestionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, qu.sqlSave, qu.mutation, qu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QuestionUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QuestionUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QuestionUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qu *QuestionUpdate) check() error {
	if v, ok := qu.mutation.Title(); ok {
		if err := question.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Question.title": %w`, err)}
		}
	}
	if v, ok := qu.mutation.Content(); ok {
		if err := question.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Question.content": %w`, err)}
		}
	}
	return nil
}

func (qu *QuestionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := qu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.ReferenceCode(); ok {
		_spec.SetField(question.FieldReferenceCode, field.TypeString, value)
	}
	if qu.mutation.ReferenceCodeCleared() {
		_spec.ClearField(question.FieldReferenceCode, field.TypeString)
	}
	if value, ok := qu.mutation.Title(); ok {
		_spec.SetField(question.FieldTitle, field.TypeString, value)
	}
	if value, ok := qu.mutation.Content(); ok {
		_spec.SetField(question.FieldContent, field.TypeString, value)
	}
	if qu.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.RemovedChoicesIDs(); len(nodes) > 0 && !qu.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	qu.mutation.done = true
	return n, nil
}

// QuestionUpdateOne is the builder for updating a single Question entity.
type QuestionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestionMutation
}

// SetReferenceCode sets the "reference_code" field.
func (quo *QuestionUpdateOne) SetReferenceCode(s string) *QuestionUpdateOne {
	quo.mutation.SetReferenceCode(s)
	return quo
}

// SetNillableReferenceCode sets the "reference_code" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableReferenceCode(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetReferenceCode(*s)
	}
	return quo
}

// ClearReferenceCode clears the value of the "reference_code" field.
func (quo *QuestionUpdateOne) ClearReferenceCode() *QuestionUpdateOne {
	quo.mutation.ClearReferenceCode()
	return quo
}

// SetTitle sets the "title" field.
func (quo *QuestionUpdateOne) SetTitle(s string) *QuestionUpdateOne {
	quo.mutation.SetTitle(s)
	return quo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableTitle(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetTitle(*s)
	}
	return quo
}

// SetContent sets the "content" field.
func (quo *QuestionUpdateOne) SetContent(s string) *QuestionUpdateOne {
	quo.mutation.SetContent(s)
	return quo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (quo *QuestionUpdateOne) SetNillableContent(s *string) *QuestionUpdateOne {
	if s != nil {
		quo.SetContent(*s)
	}
	return quo
}

// AddChoiceIDs adds the "choices" edge to the Choice entity by IDs.
func (quo *QuestionUpdateOne) AddChoiceIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.AddChoiceIDs(ids...)
	return quo
}

// AddChoices adds the "choices" edges to the Choice entity.
func (quo *QuestionUpdateOne) AddChoices(c ...*Choice) *QuestionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return quo.AddChoiceIDs(ids...)
}

// Mutation returns the QuestionMutation object of the builder.
func (quo *QuestionUpdateOne) Mutation() *QuestionMutation {
	return quo.mutation
}

// ClearChoices clears all "choices" edges to the Choice entity.
func (quo *QuestionUpdateOne) ClearChoices() *QuestionUpdateOne {
	quo.mutation.ClearChoices()
	return quo
}

// RemoveChoiceIDs removes the "choices" edge to Choice entities by IDs.
func (quo *QuestionUpdateOne) RemoveChoiceIDs(ids ...int) *QuestionUpdateOne {
	quo.mutation.RemoveChoiceIDs(ids...)
	return quo
}

// RemoveChoices removes "choices" edges to Choice entities.
func (quo *QuestionUpdateOne) RemoveChoices(c ...*Choice) *QuestionUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return quo.RemoveChoiceIDs(ids...)
}

// Where appends a list predicates to the QuestionUpdate builder.
func (quo *QuestionUpdateOne) Where(ps ...predicate.Question) *QuestionUpdateOne {
	quo.mutation.Where(ps...)
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QuestionUpdateOne) Select(field string, fields ...string) *QuestionUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Question entity.
func (quo *QuestionUpdateOne) Save(ctx context.Context) (*Question, error) {
	return withHooks(ctx, quo.sqlSave, quo.mutation, quo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QuestionUpdateOne) SaveX(ctx context.Context) *Question {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QuestionUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QuestionUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (quo *QuestionUpdateOne) check() error {
	if v, ok := quo.mutation.Title(); ok {
		if err := question.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Question.title": %w`, err)}
		}
	}
	if v, ok := quo.mutation.Content(); ok {
		if err := question.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Question.content": %w`, err)}
		}
	}
	return nil
}

func (quo *QuestionUpdateOne) sqlSave(ctx context.Context) (_node *Question, err error) {
	if err := quo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(question.Table, question.Columns, sqlgraph.NewFieldSpec(question.FieldID, field.TypeInt))
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Question.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, question.FieldID)
		for _, f := range fields {
			if !question.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != question.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.ReferenceCode(); ok {
		_spec.SetField(question.FieldReferenceCode, field.TypeString, value)
	}
	if quo.mutation.ReferenceCodeCleared() {
		_spec.ClearField(question.FieldReferenceCode, field.TypeString)
	}
	if value, ok := quo.mutation.Title(); ok {
		_spec.SetField(question.FieldTitle, field.TypeString, value)
	}
	if value, ok := quo.mutation.Content(); ok {
		_spec.SetField(question.FieldContent, field.TypeString, value)
	}
	if quo.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.RemovedChoicesIDs(); len(nodes) > 0 && !quo.mutation.ChoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.ChoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   question.ChoicesTable,
			Columns: []string{question.ChoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(choice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Question{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{question.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	quo.mutation.done = true
	return _node, nil
}
