// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/choice"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/question"
	"github.com/takechiyo-19940627/medicalquest/infrastructure/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	choiceFields := schema.Choice{}.Fields()
	_ = choiceFields
	// choiceDescContent is the schema descriptor for content field.
	choiceDescContent := choiceFields[1].Descriptor()
	// choice.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	choice.ContentValidator = choiceDescContent.Validators[0].(func(string) error)
	// choiceDescIsCorrect is the schema descriptor for is_correct field.
	choiceDescIsCorrect := choiceFields[2].Descriptor()
	// choice.DefaultIsCorrect holds the default value on creation for the is_correct field.
	choice.DefaultIsCorrect = choiceDescIsCorrect.Default.(bool)
	// choiceDescCreatedAt is the schema descriptor for created_at field.
	choiceDescCreatedAt := choiceFields[3].Descriptor()
	// choice.DefaultCreatedAt holds the default value on creation for the created_at field.
	choice.DefaultCreatedAt = choiceDescCreatedAt.Default.(func() time.Time)
	// choiceDescID is the schema descriptor for id field.
	choiceDescID := choiceFields[0].Descriptor()
	// choice.IDValidator is a validator for the "id" field. It is called by the builders before save.
	choice.IDValidator = choiceDescID.Validators[0].(func(int) error)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescTitle is the schema descriptor for title field.
	questionDescTitle := questionFields[2].Descriptor()
	// question.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	question.TitleValidator = questionDescTitle.Validators[0].(func(string) error)
	// questionDescContent is the schema descriptor for content field.
	questionDescContent := questionFields[3].Descriptor()
	// question.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	question.ContentValidator = questionDescContent.Validators[0].(func(string) error)
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionFields[4].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() time.Time)
	// questionDescID is the schema descriptor for id field.
	questionDescID := questionFields[0].Descriptor()
	// question.IDValidator is a validator for the "id" field. It is called by the builders before save.
	question.IDValidator = questionDescID.Validators[0].(func(int) error)
}
